### ISSUE TITLE
can robotjs be used in xvfb env?

### ISSUE THREAD

**Issue by xywang68** [octalmage/robotjs#267]
First, robotjs has been great in our tests.
Now we have a need to port our test to headless test environment, say xvfb. We can run all our test with xvfb-run command by assigning display :99 (or any number), however all robotjs keys are still sent to the current console.

Here is what our code snip looks like:
```
(shell)
export DISPLAY=:99
...
(java script)
var robot = require('robotjs');
robot.keyTap('down');
robot.keyTap('enter');
```
I wonder if we can make robotjs to act on a X display, say :99?

**Comment by octalmage** [comment]
This is possible, because we do it to test RobotJS. Take a look at our Travis config:

https://github.com/octalmage/robotjs/blob/master/.travis.yml

Let me know if this helps!

**Comment by octalmage** [comment]
These commands might help also:

https://github.com/octalmage/robotjs/pull/206

**Comment by xywang68** [comment]
Hi, thanks for the answer.
Suppose this is supported:
```
#if defined(USE_X11)
        #include "xdisplay.h"
#endif
```
How do I compile it to activate this feature?
I have tried on ubuntu with
```
export USE_X11=1
npm install robotjs
```
and I have a test.js with these 2 lines:
```
var robot = require('robotjs');
console.log('DISPLAY=' + robot.getXDisplay());
```
and I am still getting:
TypeError: robot.getXDisplay is not a function

**Comment by aas395** [comment]
I'm having trouble getting this to work in Xvfb on Ubuntu 16.04 LTS. I looked at related threads and couldn't find anything that helped me.

I have robotjs 0.5.1, and it sort of works for me when I'm running a nightwatch script in Ubuntu without Xvfb (the mouse moves and clicks as expected in a video recording I have, although it doesn't appear to be doing those things when the test is running). When I try to run this using Xvfb, however, the mouse doesn't move at all.

I was hoping this would just work in Xvfb without requiring me to change anything, but it looks like that's not the case and I'm not clear on what needs to change. It might be helpful to add any necessary steps for Xvfb to the documentation, as well, as I would expect I'm not the only one who's trying to do something like this.

Thank you for all your good work!

**Comment by aas395** [comment]
In case anyone else comes across this, my problem was that I wasn't telling robotjs which display to use. Assuming you set an environment variable called DISPLAY when you started Xvfb, you can use the following line to make robotjs aware that you want to control the mouse/keyboard on the Xvfb screen:

`robot.setXDisplayName(process.env.DISPLAY);`

And now everything works as I would expect. I still hope some of this stuff will make it into the documentation. Thanks again!

**Comment by kevinbarabash** [comment]
This is super cool.  I'm so happy that robot.js supports xvfb.
