### ISSUE TITLE
Unable to re-build on windows with electron version 1.7.3

### ISSUE THREAD

**Issue by poojas2288** [octalmage/robotjs#348]
Unable to rebuild robotjs on windows 7 in electron app version 1.7.3
My node version is 4.5.0.
Tried upgrading node but no change.

I tried following command : 
npm rebuild --runtime=electron --target=1.7.3 --disturl=https://atom.io/download/atom-shell --abi=54

Got error :
prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-electron-v54-win32-ia32.tar.gz

prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-electron-v54-win32-ia32.tar.gz

prebuild-install WARN install No prebuilt binaries found (target=1.7.3 runtime=electron arch=ia32 platform=win32)
## Expected Behavior
Robotjs should be rebuilt

## Current Behavior
error while rebuilding.

## Your Environment

* RobotJS version: 0.4.7
* Node.js version: 4.5.0
* npm version: 2.15.9
* electron version: 1.7.3
* Operating System: Win 7

**Comment by zttAsoiaf** [comment]
![image](https://user-images.githubusercontent.com/10683246/34006667-222b6cbe-e13a-11e7-9362-98abfcc0c73f.png)

![image](https://user-images.githubusercontent.com/10683246/34006688-390260f0-e13a-11e7-89a0-572dc0434e23.png)

when I run the command：
**npm rebuild --runtime=electron --target=1.7.9 --disturl=https://atom.io/download/atom-shell --abi=57**

when I run the command：
E:\nodejs\myfirstapp>**electron .**

App threw an error during load
Error: Cannot find module 'robotjs'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\ztt\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\nodejs\myfirstapp\main.js:6:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
^C终止批处理操作吗(Y/N)? y

how should I do???

**Comment by roy2651** [comment]
第一，你先npm install robotjs --save
第二，npm run rebuild
第三，electron .

**Comment by majoressense** [comment]
same problem

**Comment by roy2651** [comment]
@majoressense 你什么问题，环境好了嘛，这库我用了很久了，你报什么错，有截图可以看嘛

**Comment by majoressense** [comment]
@roy2651 又行了！！没事了已经

**Comment by octalmage** [comment]
Would you mind pasting the full output from npm install? The correct binary should be build if no prebuilt binaries are found.

**Comment by ysuliu** [comment]
@roy2651  能帮忙看看https://github.com/octalmage/robotjs/issues/389 这个问题吗？谢谢

**Comment by oktapodia** [comment]
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.
