### ISSUE TITLE
Install error for new LTS node v8.9.1

### ISSUE THREAD

**Issue by quinton-ashley** [octalmage/robotjs#342]
I get this error when trying to install robotjs for node v8.9.1.  I'm on macOS 10.13.1.  I need to use the new node v8.9.1 LTS to use one of my other packages in my project that relies on async and await.
```
npm i robotjs --save

> robotjs@0.4.7 install /Users/qashto/Documents/web/qodemate/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/robotjs-v0.4.7-node-v57-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/qashto/.npm/_prebuilds/https-github.com-octalmage-robotjs-releases-download-v0.4.7-robotjs-v0.4.7-node-v57-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.9.1 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
  CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
  CC(target) Release/obj.target/robotjs/src/mouse.o
  CC(target) Release/obj.target/robotjs/src/keypress.o
  CC(target) Release/obj.target/robotjs/src/keycode.o
  CC(target) Release/obj.target/robotjs/src/screen.o
  CC(target) Release/obj.target/robotjs/src/screengrab.o
  CC(target) Release/obj.target/robotjs/src/snprintf.o
  CC(target) Release/obj.target/robotjs/src/MMBitmap.o
  SOLINK_MODULE(target) Release/robotjs.node
+ robotjs@0.4.7
added 1 package and updated 38 packages in 26.14s
qashto:qodemate qashto$ node app.js
module.js:538
    throw err;
    ^

Error: Cannot find module './darwin-x64-57'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/qashto/Documents/web/qodemate/node_modules/robot-js/Library/Robot.js:16:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by syzer** [comment]
made it work for 8.9

**Comment by quinton-ashley** [comment]
It needs to work for 8.9.1 since that is the LTS version of node.

**Comment by syzer** [comment]
Have you tied 8.9.0 with --harmony flag ?

**Comment by quinton-ashley** [comment]
I'm not using 8.9.0 I'm using 8.9.1.

**Comment by quinton-ashley** [comment]
Please fix this soon!  Anyone using the current LTS version of node will not be able to install this package.

**Comment by HarrySarson** [comment]
@quinton-ashley does it work with node 8.9.0?

**Comment by quinton-ashley** [comment]
Prebuilt binaries are still not available for 8.9.1.  I don't know about 8.9.0 because I don't have it.  8.9.1 was an important security update.  Here's the full error message with harmony flag:
```
qashto$ npm i robotjs --harmony

> robotjs@0.4.7 install /Users/qashto/Documents/web/qodemate/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/robotjs-v0.4.7-node-v57-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/qashto/.npm/_prebuilds/https-github.com-octalmage-robotjs-releases-download-v0.4.7-robotjs-v0.4.7-node-v57-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v57-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.9.1 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
  CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
  CC(target) Release/obj.target/robotjs/src/mouse.o
  CC(target) Release/obj.target/robotjs/src/keypress.o
  CC(target) Release/obj.target/robotjs/src/keycode.o
  CC(target) Release/obj.target/robotjs/src/screen.o
  CC(target) Release/obj.target/robotjs/src/screengrab.o
  CC(target) Release/obj.target/robotjs/src/snprintf.o
  CC(target) Release/obj.target/robotjs/src/MMBitmap.o
  SOLINK_MODULE(target) Release/robotjs.node
+ robotjs@0.4.7
updated 1 package in 63.426s
```

**Comment by HarrySarson** [comment]
If I am not mistaken there are no error messages there. node-gyp built the binaries for you when they couldn't be fetched.

**Comment by quinton-ashley** [comment]
I get this error when I try to run my project:
```
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/Users/qashto/Documents/web/qodemate/node_modules/robotjs/build/Release/robotjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/qashto/Documents/web/qodemate/node_modules/robotjs/index.js:1:77)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

**Comment by octalmage** [comment]
Sorry for the delay, I'm working on automating this process now.
