### ISSUE TITLE
Does not work with Electron 3.0.0 please help!

### ISSUE THREAD

**Issue by quinton-ashley** [octalmage/robotjs#419]
Robotjs worked with the previous version of Electron but not the new version.

## Current Behavior
After install when running the app I get this error.
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/qashto/Documents/dev/apps/qodemate/node_modules/robotjs/build/Release/robotjs.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/qashto/Documents/dev/apps/qodemate/node_modules/robotjs/build/Release/robotjs.node
  Expected in: flat namespace
```

## Context
Trying to use robotjs in my electron based app, Qodemate.  Robotjs is the most important module of the app.

## Your Environment
* RobotJS version: 0.5.1
* Electron version: 3.0.2
* Node.js version: 10.10.0
* npm version: 6.4.1
* Operating System: macOS 10.14 Mojave

**Comment by FibreFoX** [comment]
Can't confirm this, I'm using this with latest electron 3.0.1 for controlling the mouse. But I'm using Windows and Linux, maybe this is platform-specific!

**Comment by mnakkara** [comment]
I had robotjs working with electron 3.0 on MacOS 10.13 High Sierra till yesterday.  Then I updated to MacOS 10.14 Mojave and it stopped working.

**Comment by quinton-ashley** [comment]
I also just updated to 10.14 Mojave and it does not work with Electron 3.0.2.

**Comment by quinton-ashley** [comment]
I've also tried windows 10 + electron 3.0.2 and it didn't work.  @FibreFoX are you using windows 10?  If so could you explain how you got it to rebuild correctly?

**Comment by quinton-ashley** [comment]
Do I need visual studio 2015 installed?

**Comment by mnakkara** [comment]
Robotjs mouse and keyboard are working in MacOS Mojave. You have to provide accessibility permission for the app to control your Mac. If electron Dev builds are running from vscode, you have to give permission to vscode. Usually an alert pops up asking you to give permission. I missed it the first time due to my multiple monitor seup.

**Comment by FibreFoX** [comment]
@quinton-ashley as described in the readme of RobotJS, I installed latest Visual Studio (Community Edition) and opted in for Python in version 2 (you might want to make sure NOT to have version 3 selected).

**Comment by quinton-ashley** [comment]
@FibreFoX I did have python 3 selected before which is why the build wouldn't finish, now I am using 2.7 and it builds but throws an error when it runs

**Comment by mnakkara** [comment]
@quinton-ashley did you rebuild robotjs after npm install ?  I run `npm rebuild --runtime=electron --target=3.0.0 --disturl=https://atom.io/download/atom-shell --abi=64`

**Comment by FibreFoX** [comment]
@quinton-ashley I've removed my `node_modules` folder several times, mostly to avoid conflicts with multiple compilations.

**Comment by quinton-ashley** [comment]
@mnakkara I was rebuilding it with node-gyp on windows like the readme says which wasn't working.  That command worked for me on windows!  Could this be added to the readme?

**Comment by mnakkara** [comment]
@quinton-ashley I got that command from here http://robotjs.io/docs/electron

**Comment by quinton-ashley** [comment]
@mnakkara ah I was not aware of that documentation, thank you!

**Comment by quinton-ashley** [comment]
Don't use electron v1.8.6.  Update to the node LTS and the latest version of electron and use this:
`npm rebuild --runtime=electron --target=3.0.0 --disturl=https://atom.io/download/atom-shell --abi=64`
